### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F11-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F11-1/main#200]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @kevinalvarez7 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-1/main/pull/191 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/188 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/166 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/114 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/113 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/112 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/111 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/110 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/104 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/98 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tejasvas123 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-1/main/pull/199 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/197 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/196 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/190 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/189 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/186 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/182 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/178 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/176 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/146 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/197 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/196 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/190 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/189 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/182 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/178 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/176 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/174 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/172 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/170 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/159 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/158 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/155 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/154 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/153 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/152 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/150 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/146 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/98 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/95 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @swang1997 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-1/main/pull/194 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/187 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/185 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/184 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/168 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/119 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/102 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/101 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/98 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @zhubo225 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-1/main/pull/195 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/193 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/149 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/148 https://github.com/AY1920S1-CS2113T-F11-1/main/pull/148 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/98 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/96 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/26 https://github.com/AY1920S1-CS2113T-F11-1/main/issues/25 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @andyrobert3

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
